
package Vista;

import com.sun.awt.AWTUtilities;
import java.io.IOException;
import javax.swing.JOptionPane;


public class Distribucion extends javax.swing.JFrame {
    public int x,y;
//    Esta clase basicamente son puros accesos a otras ventanas que se seleccionen en los menus
//    no hay mucho que documentar
    public Distribucion() {
        initComponents();
        setLocationRelativeTo(null);
        
        //Darle movilidad a la ventana
        
        AWTUtilities.setWindowOpaque(this, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        base_datos = new javax.swing.JMenuItem();
        listado_paises = new javax.swing.JMenuItem();
        statistics = new javax.swing.JMenuItem();
        nos = new javax.swing.JMenu();
        nosotros = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        c_sesion = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 540, 390));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\alsolis\\Desktop\\Imagenes Java\\Distribucion.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenuBar1.setBackground(new java.awt.Color(196, 196, 196));
        jMenuBar1.setForeground(new java.awt.Color(196, 196, 196));

        jMenu1.setBackground(new java.awt.Color(196, 196, 196));
        jMenu1.setForeground(new java.awt.Color(77, 92, 126));
        jMenu1.setText("Aplicaciones");

        base_datos.setText("Base de datos");
        base_datos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                base_datosActionPerformed(evt);
            }
        });
        jMenu1.add(base_datos);

        listado_paises.setText("Listado de paises");
        listado_paises.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listado_paisesActionPerformed(evt);
            }
        });
        jMenu1.add(listado_paises);

        statistics.setText("Estadisticas");
        statistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statisticsActionPerformed(evt);
            }
        });
        jMenu1.add(statistics);

        jMenuBar1.add(jMenu1);

        nos.setBackground(new java.awt.Color(196, 196, 196));
        nos.setForeground(new java.awt.Color(77, 92, 126));
        nos.setText("Acerca nosotros");
        nos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nosActionPerformed(evt);
            }
        });

        nosotros.setText("Acerca nosotros");
        nosotros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nosotrosActionPerformed(evt);
            }
        });
        nos.add(nosotros);

        jMenuBar1.add(nos);

        jMenu3.setBackground(new java.awt.Color(196, 196, 196));
        jMenu3.setForeground(new java.awt.Color(77, 92, 126));
        jMenu3.setText("Logout");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        c_sesion.setText("Cerrar Sesion");
        c_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_sesionActionPerformed(evt);
            }
        });
        jMenu3.add(c_sesion);

        exit.setText("Salir");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenu3.add(exit);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void base_datosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_base_datosActionPerformed
        Principal prin = new Principal();
        prin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_base_datosActionPerformed

    private void listado_paisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listado_paisesActionPerformed
        try{
        Lista_paises list = new Lista_paises();
        list.setVisible(true);
        this.setVisible(false);
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_listado_paisesActionPerformed

    private void statisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statisticsActionPerformed
        
        Estadisticas estad = new Estadisticas();
        estad.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_statisticsActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void nosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nosActionPerformed
    
    }//GEN-LAST:event_nosActionPerformed

    private void nosotrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nosotrosActionPerformed
        Acerca_nosotros nos = new Acerca_nosotros();
        nos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_nosotrosActionPerformed

    private void c_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_sesionActionPerformed
        Inicio ini= new Inicio();
        ini.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_c_sesionActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_jLabel2MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Distribucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Distribucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Distribucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Distribucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Distribucion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem base_datos;
    private javax.swing.JMenuItem c_sesion;
    private javax.swing.JMenuItem exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem listado_paises;
    private javax.swing.JMenu nos;
    private javax.swing.JMenuItem nosotros;
    private javax.swing.JMenuItem statistics;
    // End of variables declaration//GEN-END:variables
}
