
package Vista;

import Configuracion.Conexion;
import static com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type.Int;
import java.awt.Color;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;

public class Principal extends javax.swing.JFrame {
    Conexion con = new Conexion();
    Connection cn;
    Statement st;
    ResultSet rs;
    DefaultTableModel model;
    
    
    
    
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
        listar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        apellido1 = new javax.swing.JTextField();
        apellido2 = new javax.swing.JTextField();
        identificacion = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        pais = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        fecha = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        estado_civil = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        universidad = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        correo = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        carrera = new javax.swing.JTextField();
        observacion = new javax.swing.JTextField();
        agregar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        estado = new javax.swing.JToggleButton();
        limpiar_caja = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        edadSort = new javax.swing.JButton();
        idSort = new javax.swing.JButton();
        nombreSort = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDatos = new javax.swing.JTable();

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Nombre");

        jLabel3.setText("Primer Apellido");

        jLabel4.setText("Segundo Apellido");

        jLabel5.setText("Identificacion");

        jLabel6.setText("Pais de Origen");

        jLabel7.setText("Fecha de Nacimiento");

        jLabel9.setText("Direccion");

        jLabel12.setText("Estado Civil");

        apellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellido1ActionPerformed(evt);
            }
        });

        apellido2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellido2ActionPerformed(evt);
            }
        });

        identificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identificacionActionPerformed(evt);
            }
        });

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        jLabel13.setText("Numero de estudiante");

        id.setEnabled(false);

        estado_civil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin especificar", "Soltero (a)", "Casado (a)", "Union Libre", "Divorciado (a)", "Viudo (a)" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(apellido1)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12))
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(estado_civil, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pais, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(direccion, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(129, 129, 129)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel7)
                        .addComponent(apellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel12)
                    .addComponent(identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estado_civil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel8.setText("Universidad");

        jLabel10.setText("Numero de telefono");

        jLabel11.setText("Correo Electronico");

        jLabel14.setText("Observaciones Adicionales");

        jLabel15.setText("Estado");

        jLabel16.setText("Carrera");

        agregar.setText("Agregar Estudiante");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        eliminar.setText("Eliminar Estudiante");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        modificar.setText("Modificar Estudiante");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        estado.setText("Inactivo");
        estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoActionPerformed(evt);
            }
        });

        limpiar_caja.setText("Limpiar cajas");
        limpiar_caja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiar_cajaActionPerformed(evt);
            }
        });

        jLabel17.setText("Ordenar por:");

        edadSort.setText("Edad");
        edadSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edadSortActionPerformed(evt);
            }
        });

        idSort.setText("Identificacion");
        idSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idSortActionPerformed(evt);
            }
        });

        nombreSort.setText("Nombre");
        nombreSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreSortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(agregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(limpiar_caja, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(jLabel17)
                        .addGap(14, 14, 14)
                        .addComponent(nombreSort, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(idSort, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edadSort, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(telefono, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(universidad)
                            .addComponent(correo))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(27, 27, 27)
                                        .addComponent(carrera, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(68, 68, 68)
                                        .addComponent(jLabel15)
                                        .addGap(0, 649, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(observacion)))
                                .addContainerGap())
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(403, 403, 403)
                                .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(universidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)
                        .addComponent(carrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(observacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregar)
                    .addComponent(eliminar)
                    .addComponent(modificar)
                    .addComponent(limpiar_caja)
                    .addComponent(jLabel17)
                    .addComponent(edadSort)
                    .addComponent(idSort)
                    .addComponent(nombreSort))
                .addContainerGap())
        );

        TablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id de Registro", "Nombre", "Primer Apellido", "Segundo Apellido", "Identificacion", "Carrera", "Estado Civil", "Pais de Origen", "Direccion", "Edad", "Universidad", "Telefono", "Correo", "Estado", "Observaciones"
            }
        ));
        TablaDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaDatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void apellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellido1ActionPerformed

    private void apellido2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellido2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellido2ActionPerformed

    private void identificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_identificacionActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        agregar();
        vaciar_cajas();
        limpiar();
        listar();
    }//GEN-LAST:event_agregarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        eliminar();
        vaciar_cajas();
        limpiar();
        listar();
    }//GEN-LAST:event_eliminarActionPerformed

    private void TablaDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDatosMouseClicked
        int fila = TablaDatos.getSelectedRow();
        
        if(fila == -1){
            JOptionPane.showMessageDialog(null, "Usuario no seleccionado");
       }else{
           
           String estud = (String)TablaDatos.getValueAt(fila, 0);
           String nom = (String)TablaDatos.getValueAt(fila, 1);
           String apel1 = (String)TablaDatos.getValueAt(fila, 2);
           String apel2 = (String)TablaDatos.getValueAt(fila, 3);
           String iden = (String)TablaDatos.getValueAt(fila, 4);
           String carrer = (String)TablaDatos.getValueAt(fila, 5);
           String civil = (String)TablaDatos.getValueAt(fila, 6);
           String origen = (String)TablaDatos.getValueAt(fila, 7);
           String direcc = (String)TablaDatos.getValueAt(fila, 8);
           String uni = (String)TablaDatos.getValueAt(fila, 10);
           String phone = (String)TablaDatos.getValueAt(fila, 11);
           String email = (String)TablaDatos.getValueAt(fila, 12);
           String status = (String)TablaDatos.getValueAt(fila, 13);
           String obs = (String)TablaDatos.getValueAt(fila, 14);
           boolean estado;
           
           if(status.equals("Activo")){
               estado = true;
               this.estado.setBackground(new Color(82, 146, 6));
               this.estado.setText("Activo");
           }else{
               estado = false;
               this.estado.setBackground(new Color (187,187,187));
               this.estado.setText("Inactivo");
           }

           String sql= "Select fecha_de_nacimiento from principal where idprincipal = "+ estud;
           try{
               cn= con.getConnection();
               st= cn.createStatement();
               rs= st.executeQuery(sql);
               while(rs.next()){
                    String fecha1 = rs.getString("fecha_de_nacimiento");

                    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
                    Date date1 = formato.parse(fecha1);

                    id.setText(estud);
                    nombre.setText(nom);
                    apellido1.setText(apel1);
                    apellido2.setText(apel2);
                    identificacion.setText(iden);
                    carrera.setText(carrer);
                    estado_civil.setSelectedItem(civil);
                    pais.setText(origen);
                    direccion.setText(direcc);
                    fecha.setDate(date1);
                    universidad.setText(uni);
                    telefono.setText(phone);
                    correo.setText(email);
                    this.estado.setSelected(estado);
                    
                    observacion.setText(obs);
               }
               
            
               
               
           }catch(Exception ex){
               JOptionPane.showMessageDialog(null, ex);
           }
           
           
           
        }
    }//GEN-LAST:event_TablaDatosMouseClicked

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        try{
            modificar();
            limpiar();
            listar();
        }catch(java.lang.NullPointerException ex){
            JOptionPane.showMessageDialog(null, "Debe de seleccionar algo de la lista");
        }
    }//GEN-LAST:event_modificarActionPerformed

    private void limpiar_cajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiar_cajaActionPerformed
        vaciar_cajas();
    }//GEN-LAST:event_limpiar_cajaActionPerformed

    private void estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoActionPerformed
        if(estado.isSelected()){
            estado.setBackground(new Color(82, 146, 6));
            estado.setText("Activo");
        }else{
            estado.setBackground(new Color (187,187,187));
            estado.setText("Inactivo");
        }
    }//GEN-LAST:event_estadoActionPerformed

    private void nombreSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreSortActionPerformed
        
    }//GEN-LAST:event_nombreSortActionPerformed

    private void idSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idSortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idSortActionPerformed

    private void edadSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edadSortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edadSortActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Principal().setVisible(true);
//            }
//        });
//    }
    void vaciar_cajas(){
        id.setText(null);
        nombre.setText("");
        apellido1.setText("");
        apellido2.setText("");
        identificacion.setText("");
        carrera.setText("");
        estado_civil.setSelectedItem("Sin especificar");
        pais.setText("");
        direccion.setText("");
        fecha.setDate(null);
        universidad.setText("");
        telefono.setText("");
        correo.setText("");
        estado.setSelected(false);
        observacion.setText("");
        estado.setBackground(new Color (187,187,187));
        estado.setText("Inactivo");
    }
    void modificar(){
        
        String ida = id.getText();
        String nom = nombre.getText();
        String ap1 = apellido1.getText();
        String ap2 = apellido2.getText();
        String id = identificacion.getText();
        String carrer = carrera.getText();
        String civil = (String)estado_civil.getSelectedItem();
        String p_origen = pais.getText();
        String direc = direccion.getText();
        String uni = universidad.getText();
        String cell = telefono.getText();
        String email = correo.getText();
        boolean status = estado.isSelected();
        String obs = observacion.getText();
        
        //        Obtener fecha

        Date nacimiento = fecha.getDate();
        LocalDate ahora = LocalDate.now();
        LocalDate fecha_nacimiento;
        DateTimeFormatter fmt = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        String fechaCadena = formato.format(nacimiento);
        fecha_nacimiento = LocalDate.parse(fechaCadena, fmt);
        Period periodo = Period.between(fecha_nacimiento, ahora);
        String años = String.valueOf(periodo.getYears());
        String meses = String.valueOf(periodo.getMonths());
        String dias = String.valueOf(periodo.getDays());
        String edad =  años + " años " + meses + " meses "+dias+" dias" ;
        
        //Manejo de activos e inactivos
        String estado;
        
        if(status==true){
            estado ="Activo";
        }else{
            estado="Inactivo";
        }
        
        if(nom.equals("")||ap1.equals("")||ap2.equals("")||id.equals("")||carrer.equals("")||civil.equals("")||
            p_origen.equals("")||direc.equals("")||uni.equals("")||cell.equals("")||
            email.equals("")){
            
            JOptionPane.showMessageDialog(null, "Falto uno o mas valores de ingresar");
        }else{
            String sql = "update principal set nombre='"+nom+"',primer_apellido='"+ap1+"',segundo_apellido='"+ap2+"',identificacion='"+id+"',carrera='"+carrer+
                "',estado_civil='"+civil+"',pais_de_origen='"+p_origen+"',direccion='"+direc+"',fecha_de_nacimiento='"+fechaCadena+
                "',edad='"+edad+"',universidad='"+uni+"',telefono='"+cell+"',correo='"+email+"',estado='"+estado+"',observaciones='"+obs+"' where idprincipal="+ida;
            try{
                cn=con.getConnection();
                st=cn.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Registro actualizado");
                vaciar_cajas();
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex);
            }
        } 
    }
    
    void eliminar(){
        int fila = TablaDatos.getSelectedRow();
        String ida = (String)TablaDatos.getValueAt(fila, 0);
        
        String sql = "delete from principal where idprincipal = "+ida;
        try{
            
            cn=con.getConnection();
            st=cn.createStatement();
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Eliminado");
            
        
        }catch(Exception ex){
            
            JOptionPane.showMessageDialog(null, ex);
            
        }
       
    }
    
    void listar(){
        
        String sql = "Select * from principal";
        try{
        cn= con.getConnection();
        st= cn.createStatement();
        rs= st.executeQuery(sql); 
        Object[]estudiante = new Object[16];
        model = (DefaultTableModel) TablaDatos.getModel();
        while(rs.next()){
            
            estudiante[0]=rs.getString("idprincipal");
            estudiante[1]=rs.getString("nombre");
            estudiante[2]=rs.getString("primer_apellido");
            estudiante[3]=rs.getString("segundo_apellido");
            estudiante[4]=rs.getString("identificacion");
            estudiante[5]=rs.getString("carrera");
            estudiante[6]=rs.getString("estado_civil");
            estudiante[7]=rs.getString("pais_de_origen");
            estudiante[8]=rs.getString("direccion");
            estudiante[9]=rs.getString("edad");
            estudiante[10]=rs.getString("universidad");
            estudiante[11]=rs.getString("telefono");
            estudiante[12]=rs.getString("correo");
            estudiante[13]=rs.getString("estado");
            estudiante[14]=rs.getString("observaciones");
            model.addRow(estudiante);
        }
        TablaDatos.setModel(model);
        
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
            
        }
        
    }
    void limpiar(){
        for (int i = 0; i < TablaDatos.getRowCount(); i++) {
            model.removeRow(i);
            i--;
        }
    }
            
    void agregar(){
        boolean condicion = false;
        String nom = nombre.getText();
        String ap1 = apellido1.getText();
        String ap2 = apellido2.getText();
        String id = identificacion.getText();
        String carrer = carrera.getText();
        String civil = (String)estado_civil.getSelectedItem();
        String p_origen = pais.getText();
        String direc = direccion.getText();
        String uni = universidad.getText();
        String cell = telefono.getText();
        String email = correo.getText();
        boolean status = this.estado.isSelected();
        String obs = observacion.getText();
        String estado;
        
        if(status==true){
            estado ="Activo";
        }else{
            estado="Inactivo";
        }
        
        
        
        
        
        try{
            Date nacimiento = fecha.getDate();
            LocalDate ahora = LocalDate.now();
            LocalDate fecha_nacimiento;
            DateTimeFormatter fmt = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            String fechaCadena = formato.format(nacimiento);
            fecha_nacimiento = LocalDate.parse(fechaCadena, fmt);
            Period periodo = Period.between(fecha_nacimiento, ahora);
            String años = String.valueOf(periodo.getYears());
            String meses = String.valueOf(periodo.getMonths());
            String dias = String.valueOf(periodo.getDays());
            String edad =  años + " años " + meses + " meses "+dias+" dias" ;
            

            if(nom.equals("")||ap1.equals("")||ap2.equals("")||id.equals("")||carrer.equals("")||civil.equals("")||
                    p_origen.equals("")||direc.equals("")||uni.equals("")||cell.equals("")||
                    email.equals("")||condicion == true){

                JOptionPane.showMessageDialog(null, "Falto uno o mas valores de ingresar");
                condicion = false;
            }else{
                
                String sql = "insert into principal(nombre, primer_apellido, segundo_apellido, identificacion, carrera, estado_civil, pais_de_origen, direccion, fecha_de_nacimiento, edad, universidad, telefono, correo, estado, observaciones)values('"+nom+"', '"+ap1+"', '"+ap2+"', '"+id+"', '"+carrer+"', '"+civil+"', '"+p_origen+"', '"+direc+"', '"+fechaCadena+"', '"+edad+"', '"+uni+"', '"+cell+"', '"+email+"','"+estado+"', '"+obs+"')";
                try{
                    
                    
                    cn = con.getConnection();
                    st = cn.createStatement();
                    st.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null,"Usuario Agregado");
                    
                }catch(Exception ex){
                    JOptionPane.showMessageDialog(null, ex);
                }
            }    



        }catch(java.lang.NullPointerException ex){
            condicion = true;
        }
        
        
        
        
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaDatos;
    private javax.swing.JButton agregar;
    private javax.swing.JTextField apellido1;
    private javax.swing.JTextField apellido2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField carrera;
    private javax.swing.JTextField correo;
    private javax.swing.JTextField direccion;
    private javax.swing.JButton edadSort;
    private javax.swing.JButton eliminar;
    private javax.swing.JToggleButton estado;
    private javax.swing.JComboBox<String> estado_civil;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JTextField id;
    private javax.swing.JButton idSort;
    private javax.swing.JTextField identificacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpiar_caja;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField nombre;
    private javax.swing.JButton nombreSort;
    private javax.swing.JTextField observacion;
    private javax.swing.JTextField pais;
    private javax.swing.JTextField telefono;
    private javax.swing.JTextField universidad;
    // End of variables declaration//GEN-END:variables
}
